### ISSUE TITLE
ApplicationHost2 won't build with beta4-11271 on Linux and OS X.

### ISSUE THREAD

**Issue by lefb766** [aspnet/dnx#1410]
`kpm build` under src/Microsoft.Framework.ApplicationHost2 gives me bunch of compile errors. Each of the errors is labelled with one of two common messages shown below.
- `error CS0234: The type or namespace 'Internal' does not exist in the namespace 'Microsoft.Framework' (are you missing an assembly reference?)`
- `error CS0246: The type or namespace 'NotNull' could not be found (are you missing a using directive or an assembly reference?)`

I do not forget to clone submodules, and that `kpm restore` seems successful.

I found that it goes ok with beta4-11245, so there might be some regression since that version, or we have just encountered a bug of mono.

**Comment by lefb766** [comment]
It goes ok with beta4-11257 and fails with beta4-11268.

**Comment by davidfowl** [comment]
I'm seeing the same.

**Comment by davidfowl** [comment]
Found the issue.

**Comment by davidfowl** [comment]
@ChengTian can you make sure this bug gets fixed with #1299?

**Comment by ChengTian** [comment]
I checked in #1299 , however, that PR doesn't fix this issue. Need further investigation in this issue.

**Comment by davidfowl** [comment]
Did you modify the shared file logic in the nuget resolver?
