### ISSUE TITLE
System.ArgumentNullException on coreclr linux, for dnu build on project.json with embedded items

### ISSUE THREAD

**Issue by IRooc** [aspnet/dnx#2187]
For the following project.json:
```json
{
    "version": "1.0.0-*",
    "dependencies": {
        "Microsoft.AspNet.FileProviders.Embedded": "1.0.0-*"
    },
    "commmands":{
        "run":"run"
    },

    "resource" : "test.txt",

    "frameworks": {
        "dnx451": { },
        "dnxcore50": {
			"dependencies":{
				"System.Console": "4.0.0-beta-*"
			}
		}
    }
}
```
with the following program (which does not matter because the build failes on the project.json itself)
```c#
using System;
using System.IO;
using System.Reflection;
using Microsoft.AspNet.FileProviders;

namespace TestDnx {
	public class Program
	{
		public void Main(string[] args){
			var txt = FileContent();
			Console.WriteLine(txt);
		}


		public string FileContent() {
			Console.WriteLine(GetType().GetTypeInfo().Assembly + " " + GetType().Namespace);
			var provider = new EmbeddedFileProvider(GetType().GetTypeInfo().Assembly, GetType().Namespace);

			var fileInfo = provider.GetFileInfo("test.txt");
			using (var stream = fileInfo.CreateReadStream())
			{
				StreamReader reader = new StreamReader(stream);    
				return reader.ReadToEnd();
			}
		}

	}
}
```

when calling dnu build on linux (ubuntu 14.04 lts) for framework **1.0.0-beta6-12170 coreclr x64** the following exception is thrown:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: paths
   at System.IO.Path.Combine(String[] paths)
   at Microsoft.Framework.Runtime.GacDependencyResolver.<GetGacSearchPaths>d__6.MoveNext()
   at Microsoft.Framework.Runtime.GacDependencyResolver.TryResolvePartialName(String name, SemanticVersion version, String& assemblyLocation)
   at Microsoft.Framework.Runtime.GacDependencyResolver.GetDescription(LibraryRange libraryRange, FrameworkName targetFramework)
   at Microsoft.Framework.Runtime.WalkContext.Resolve(Dictionary`2 resolvedItems, IEnumerable`1 providers, LibraryRange packageKey, FrameworkName frameworkName)
   at Microsoft.Framework.Runtime.WalkContext.<>c__DisplayClass1_0.<Walk>b__0(Node node)
   at Microsoft.Framework.Runtime.WalkContext.<>c__DisplayClass4_0.<ForEach>b__0(Node node, Int32 _)
   at Microsoft.Framework.Runtime.WalkContext.ForEach[TState](Node root, TState state, Func`3 visitor)
   at Microsoft.Framework.Runtime.WalkContext.ForEach(Node root, Action`1 visitor)
   at Microsoft.Framework.Runtime.WalkContext.Walk(IEnumerable`1 dependencyResolvers, String name, SemanticVersion version, FrameworkName frameworkName)
   at Microsoft.Framework.Runtime.DependencyWalker.Walk(String name, SemanticVersion version, FrameworkName targetFramework)
   at Microsoft.Framework.PackageManager.BuildContext.<>c__DisplayClass16_0.<GetApplicationHostContext>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.<>c__DisplayClass0_0`1.<Get>b__0(CacheContext ctx)
   at Microsoft.Framework.Runtime.Caching.Cache.CreateEntry(Object k, Func`2 acquire)
   at Microsoft.Framework.Runtime.Caching.Cache.<>c__DisplayClass5_0.<AddEntry>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Framework.Runtime.Caching.Cache.Get(Object key, Func`2 factory)
   at Microsoft.Framework.Runtime.Caching.CacheExtensions.Get[T](ICache cache, Object key, Func`2 factory)
   at Microsoft.Framework.PackageManager.BuildContext.GetApplicationHostContext(Project project, FrameworkName targetFramework, String configuration)
   at Microsoft.Framework.PackageManager.BuildContext..ctor(IServiceProvider hostServices, IApplicationEnvironment appEnv, ICache cache, ICacheContextAccessor cacheContextAccessor, Project project, FrameworkName targetFramework, String configuration, String outputPath)
   at Microsoft.Framework.PackageManager.BuildManager.BuildInternal(String projectPath)
   at Microsoft.Framework.PackageManager.BuildManager.Build()
   at Microsoft.Framework.PackageManager.BuildConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)

```

it works fine in the MONO version, and on windows for full and coreclr

**Comment by BrennanConroy** [comment]
Fixed by #1692 once it goes in.

**Comment by BrennanConroy** [comment]
Can you check this? Should be fixed in latest.

**Comment by IRooc** [comment]
still fails on CoreCLR-x64-1.0.0-beta6-12232 is this the latest?

dnu build output:
```
Microsoft .NET Development Utility CoreCLR-x64-1.0.0-beta6-12232


Building Proj2 for DNX,Version=v4.5.1
  Using Project dependency Proj2 1.0.0
    Source: /home/rooc/Documents/Projects/Test1/Proj2/project.json

  Using Package dependency Microsoft.AspNet.FileProviders.Embedded 1.0.0-beta6-11634
    Source: /home/rooc/.dnx/packages/Microsoft.AspNet.FileProviders.Embedded/1.0.0-beta6-11634
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at NuGet.PathUtility.GetRelativeUri(String path1, String path2)
   at NuGet.PathUtility.GetRelativePath(String path1, String path2, Char separator)
   at NuGet.PathUtility.GetRelativePath(String path1, String path2)
   at Microsoft.Framework.PackageManager.BuildContext.ShowDependencyInformation(IReport report)
   at Microsoft.Framework.PackageManager.BuildContext.Initialize(IReport report)
   at Microsoft.Framework.PackageManager.BuildManager.BuildInternal(String projectPath)
   at Microsoft.Framework.PackageManager.BuildManager.Build()
   at Microsoft.Framework.PackageManager.BuildConsoleCommand.<>c__DisplayClass0_0.<Register>b__1()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Framework.PackageManager.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)

```

**Comment by BrennanConroy** [comment]
This is a known issue, please track it at #1793

**Comment by IRooc** [comment]
Just to make sure, this is the dnx . run output: Seems the same but different callstack
```
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at NuGet.PathUtility.GetRelativeUri(String path1, String path2)
   at NuGet.PathUtility.GetRelativePath(String path1, String path2, Char separator)
   at NuGet.PathUtility.GetRelativePath(String path1, String path2)
   at Microsoft.Framework.Runtime.ResourcePathUtility.GetResourceName(String projectFolder, String resourcePath)
   at Microsoft.Framework.Runtime.EmbeddedResourceProvider.<>c__DisplayClass0_0.<GetResources>b__1(KeyValuePair`2 resourceFile)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Framework.Runtime.EmbeddedResourceProvider.GetResources(ICompilationProject project)
   at Microsoft.Framework.Runtime.CompositeResourceProvider.<>c__DisplayClass3_0.<GetResources>b__0(IResourceProvider provider)
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Framework.Runtime.CompositeResourceProvider.GetResources(ICompilationProject project)
   at Microsoft.Framework.Runtime.ProjectLibraryExportProvider.<>c__DisplayClass5_0.<GetLibraryExport>b__4()
   at Microsoft.Framework.Runtime.Roslyn.RoslynCompiler.<>c__DisplayClass8_0.<CompileProject>b__1()
   at Microsoft.Framework.Runtime.Roslyn.CompilationContext.ResolveResources()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Framework.Runtime.Roslyn.CompilationContext.LazyList`1.GetEnumerator()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Compilation.ReportManifestResourceDuplicates(IEnumerable`1 manifestResources, IEnumerable`1 addedModuleNames, IEnumerable`1 addedModuleResourceNames, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileImpl(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Stream win32Resources, Stream xmlDocStream, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, CancellationToken cancellationToken)
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.Load(IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
   at dnx.host.LoaderContainer.Load(AssemblyName assemblyName)
   at dnx.host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Framework.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.LoadContext.Microsoft.Framework.Runtime.IAssemblyLoadContext.Load(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.AssemblyLoadContextExtensions.Load(IAssemblyLoadContext loadContext, String name)
   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)

```
