### ISSUE TITLE
"dnx restore" will modify/update lock files and remove "uap10.0" target

### ISSUE THREAD

**Issue by teamneusta** [aspnet/dnx#2687]
We are creating a Windows 10 universal app and plan to compile it on a Teamcity server. To make this run, we figured out that it is neccessary to run the following commands:

```
   call dnvm use default -r coreclr
   call dnu restore
   msbuild app.sln
```

Unfortunately, this ends up in an error that platform uap10.0 is not supported, because dns "dnu restore" command rewrites the project.json.lock files. The "uap10.0" target is removed and a "dnx" target is added.

Any ideas?

**Comment by muratg** [comment]
What's the DNX version you're using?  I believe we're currently raising errors instead of silently changing the target.

**Comment by muratg** [comment]
https://github.com/aspnet/dnx/issues/2302

**Comment by muratg** [comment]
@teamneusta Can you try the latest dnx (`dnvm upgrade -u`)?  This should work now with: https://github.com/aspnet/dnx/commit/18d404167451b6fd256700f4c903b7f43af3278f

**Comment by muratg** [comment]
Closing this one. If you still have the issue please feel free to file another bug. Thanks!

**Comment by teamneusta** [comment]
msbuild still fails on our build server. Problem now is that packages are restore in .dnx\packages\, but msbuild searches for packages in .nuget\packages directory.

**Comment by davidfowl** [comment]
@teamneusta We'll be unifying that in a later release, you can override it with by setting the NUGET_PACKAGES environment variable.
