### ISSUE TITLE
dnu restore/pack/build etc throws a NullReferenceException when project.json is in the root directory of a drive

### ISSUE THREAD

**Issue by ddobric** [aspnet/dnx#2752]
I created an application in folder "C:\temp\netcoreapp\src\netcoreapp".
After  executing subset q: "C:\temp\netcoreapp\src\netcoreapp" following fails:
q:\dnu restore

Exception:

```
Q:\>dnu restore project.json
Microsoft .NET Development Utility CLR-x86-1.0.0-beta8-15120

Restoring packages for Q:\project.json
----------
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.PathUtility.GetDirectoryName(String path)
   at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass60_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__60.MoveNext()
----------
Restore failed
Object reference not set to an instance of an object.

NuGet Config files used:
    C:\ProgramData\NuGet\Config\ServiceFabric.config
    C:\Users\ddobric.DAENET\AppData\Roaming\NuGet\NuGet.Config
```

**Comment by muratg** [comment]
Got a repro:

```
Y:\Src\repro>q:
The system cannot find the drive specified.

Y:\Src\repro>subst q: y:\Src\repro

Y:\Src\repro>q:

Q:\>dir
 Volume in drive Q is Shared Folders

 Directory of Q:\

09/23/2015  02:08 PM    <DIR>          .
09/23/2015  10:54 AM    <DIR>          ..
09/23/2015  11:08 AM               166 program.cs
09/23/2015  11:07 AM               448 project.json
09/23/2015  02:08 PM            81,468 project.lock.json
               3 File(s)         82,082 bytes
               2 Dir(s)  234,235,289,600 bytes free

Q:\>dnu restore
Microsoft .NET Development Utility CLR-x86-1.0.0-beta8-15618

  CACHE https://api.nuget.org/v3/index.json
Restoring packages for Q:\project.json
----------
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.PathUtility.GetDirectoryName(String path)
   at Microsoft.Dnx.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
Object reference not set to an instance of an object.

NuGet Config files used:
    C:\Users\mgirgin\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://az320820.vo.msecnd.net/v3-flatcontainer/

Q:\>
```

**Comment by muratg** [comment]
Additionally `dnu pack`, `dnu build` etc also fail with an `NullReferenceException` on `NuGet.PathUtility.GetDirectoryName`

**Comment by muratg** [comment]
This also repro's when you have a project.json on the root of any drive. I.e. if you had a `c:\project.json`, and try `dnu restore` there, it would fail as well. 

@ddobric You can `subst q: C:\temp\netcoreapp\src\` and try `dnu restore` under `q:\ netcoreapp` instead.

**Comment by iSynaptic** [comment]
I can reproduce.

**Comment by ddobric** [comment]
It works fine if I don't subst the root .thanks for hint.

**Comment by anurse** [comment]
DNX does not support projects at the root of any drive (even a subst-ed drive) because it uses the parent directory name as the project name.

**Comment by iSynaptic** [comment]
Even if that is the case, I think it should probably provide a better error/exception that NullReferenceException.

**Comment by davidfowl** [comment]
That error has been fixed since. I assume this is beta7

**Comment by iSynaptic** [comment]
Yes, beta 7.

**Comment by muratg** [comment]
@davidfowl It still throws a `NullReferenceException` in beta 8.  See https://github.com/aspnet/dnx/issues/2752#issuecomment-142744796

**Comment by muratg** [comment]
Moving to backlog as the workaround is simple. We'll see if we get other complaints and can consider it in the future.
